apiVersion: v1
kind: Service
metadata:
  name: shyaway-dashboard-service
spec:
  selector:
    app: shyaway-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      nodePort: 30851        # fixed port — access via: minikube ip :30851
  type: NodePort
